apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuapp-deployment
  labels:
    app: meuapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meuapp
  template:
    metadata:
      labels:
        app: meuapp
    spec:
      containers:
      - name: meuapp
        image: meuapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: meuapp-service
spec:
  type: NodePort
  selector:
    app: meuapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

