apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuapp-deployment
  labels:
    app: meuapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meuapp
  template:
    metadata:
      labels:
        app: meuapp
    spec:
      containers:
      - name: meuapp
        image: nginx:latest
        volumeMounts:
        - name: conteudo-estatico
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: conteudo-estatico
        configMap:
          name: meuapp-estatico
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meuapp-estatico
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Meu App Estático</title>
      </head>
      <body>
        <h1>Hello, DevOps!</h1>
      </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: meuapp-service
spec:
  type: NodePort
  selector:
    app: meuapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

